Repository CodeForAfrica/gmmp, pull requests merged in 2020-09, with the labels that each got.

#71 Special questions
  forms/admin.py
  forms/models.py
  gmmp/admin.py
  gmmp/migrations/0004_specialquestions.py
  gmmp/models.py
Labels: enhancement

#70 Work on feedback provided on current UI
  forms/admin.py
  forms/locale/en/LC_MESSAGES/django.po
  forms/locale/es/LC_MESSAGES/django.po
  forms/locale/fr/LC_MESSAGES/django.po
  forms/models.py
  forms/modelutils.py
  gmmp/locale/en/LC_MESSAGES/django.po
  gmmp/locale/es/LC_MESSAGES/django.po
  gmmp/locale/fr/LC_MESSAGES/django.po
  gmmp/settings.py
  gmmp/templates/admin/base_site.html
  gmmp/templates/admin/change_form.html
  gmmp/templates/admin/submit_line.html
  static/js/tabs.js
Labels: enhancement

#73 [Feature] Special questions from GSheet
  docker-compose.yml
  forms/admin.py
  forms/migrations/0051_increate_people_in_the_news_age.py
  gmmp/admin.py
  gmmp/migrations/0005_special_questions_gsheet_integration.py
  gmmp/models.py
  gmmp/settings.py
  gmmp/signals.py
  gmmp/urls.py
  requirements.txt
Labels: dependencies, enhancement

#76 Make Optional People Questions Required if 'yes' is Selected
  forms/static/forms/admin/dependency_fields.js
Labels: enhancement

#75 [chore] Mutli-stage Builds
  Dockerfile
  contrib/docker/cmd.sh
  contrib/docker/entrypoint.sh
  docker-compose.yml
  forms/locale/es/LC_MESSAGES/django.po
  forms/locale/fr/LC_MESSAGES/django.po
Labels: bug, chore

#74 Ft add short questions
  forms/admin.py
  forms/migrations/0052_make_fields_nullable_20200907_0936.py
  forms/migrations/0053_add_monitoring_mode_20200909_1013.py
  forms/models.py
  forms/modelutils.py
  forms/static/forms/admin/dependency_fields.js
  forms/static/forms/admin/dependent_fields.js
Labels: enhancement

#79 [Fix] Docker CMD parameters
  Dockerfile
  contrib/docker/cmd.sh
  docker-compose.yml
Labels: bug, chore

#80 [Feature] Monitor mode messages
  forms/admin.py
  forms/locale/en/LC_MESSAGES/django.po
  forms/locale/es/LC_MESSAGES/django.po
  forms/locale/fr/LC_MESSAGES/django.po
  forms/migrations/0054_monitoring_mode_messages_20200910_1441.py
  forms/modelutils.py
  forms/static/forms/admin/dependent_fields.js
  gmmp/locale/en/LC_MESSAGES/django.po
  gmmp/locale/es/LC_MESSAGES/django.po
  gmmp/locale/fr/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.po
  locale/fr/LC_MESSAGES/django.po
Labels: bug, enhancement

#78 [PATCH] Error Notification on Person Tab
  forms/admin.py
  forms/static/forms/admin/check_tab_errors/check.js
  forms/static/forms/admin/check_tab_errors/internetnewsperson.js
  forms/static/forms/admin/check_tab_errors/newspaperperson.js
  forms/static/forms/admin/check_tab_errors/radioperson.js
  forms/static/forms/admin/check_tab_errors/televisionperson.js
Labels: bug

#82 [Chore] Dokku CD
  .github/workflows/main.yml
Labels: chore

#81 Hot fix
  forms/admin.py
  forms/locale/en/LC_MESSAGES/django.po
  forms/locale/es/LC_MESSAGES/django.po
  forms/locale/fr/LC_MESSAGES/django.po
  forms/migrations/0055_remove_defaults.py
  forms/migrations/0056_allow_blank_and_none.py
  forms/modelutils.py
  forms/static/forms/admin/check_tab_errors/check.js
  forms/static/forms/admin/dependent_fields.js
  gmmp/locale/en/LC_MESSAGES/django.po
  gmmp/locale/es/LC_MESSAGES/django.po
  gmmp/locale/fr/LC_MESSAGES/django.po
  static/js/tabs.js
Labels: bug

#83 Ft add monitor code
  forms/admin.py
  forms/locale/en/LC_MESSAGES/django.po
  forms/locale/es/LC_MESSAGES/django.po
  forms/locale/fr/LC_MESSAGES/django.po
  forms/migrations/0057_add_monitor_code.py
  forms/modelutils.py
Labels: enhancement

#86 Fix reports generation
  forms/modelutils.py
  reports/report_builder.py
Labels: bug

#88 Use custom views for password reset and password reset done views.
  gmmp/urls.py
  gmmp/views.py
Labels: bug

#92 Limit Content by User Country
  forms/admin.py
  gmmp/dashboard_modules.py
Labels: enhancement

#98 Send Mass Welcome Email to Users
  .env/.env.template
  .gitignore
  gmmp/management/commands/bulk_password_reset_emails.py
  gmmp/management/commands/sync_users.py
  gmmp/models.py
  gmmp/settings.py
  gmmp/templates/emails/welcome_password_reset.html
  requirements.txt
Labels: enhancement
