Repository CodeForAfrica/gmmp, pull requests merged in 2020-08, with the labels that each got.

#59 [Chore] Cleanup
  .gitignore
  requirements.txt
Labels: chore, dependencies

#62 [Feature] Question Z
  forms/admin.py
  forms/locale/en/LC_MESSAGES/django.po
  forms/locale/es/LC_MESSAGES/django.po
  forms/locale/fr/LC_MESSAGES/django.po
  forms/migrations/0047_auto_20200820_0609.py
  forms/migrations/0048_auto_20200820_0646.py
  forms/migrations/0049_auto_20200820_0739.py
  forms/models.py
  forms/modelutils.py
  gmmp/locale/en/LC_MESSAGES/django.po
  gmmp/locale/es/LC_MESSAGES/django.po
  gmmp/locale/fr/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.po
  locale/fr/LC_MESSAGES/django.po
Labels: enhancement

#63 [Feature] Question Z Translations
  forms/locale/en/LC_MESSAGES/django.po
  forms/locale/es/LC_MESSAGES/django.po
  forms/locale/fr/LC_MESSAGES/django.po
  gmmp/locale/en/LC_MESSAGES/django.po
  gmmp/locale/es/LC_MESSAGES/django.po
  gmmp/locale/fr/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.po
  locale/fr/LC_MESSAGES/django.po
Labels: enhancement

#64 [Bug] Fix Age Input Not Showing in Twitter Add Page
  forms/admin.py
Labels: bug

#65 [Feature] Increase Age Range of People in The News
  forms/locale/en/LC_MESSAGES/django.po
  forms/locale/es/LC_MESSAGES/django.po
  forms/locale/fr/LC_MESSAGES/django.po
  forms/modelutils.py
  gmmp/locale/en/LC_MESSAGES/django.po
  gmmp/locale/es/LC_MESSAGES/django.po
  gmmp/locale/fr/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.po
  locale/fr/LC_MESSAGES/django.po
Labels: enhancement

#66 Uniquify story names
  forms/migrations/0050_add_created_and_updated_at.py
  forms/models.py
Labels: enhancement

#68 Add Pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#67 Use javascript to dynamically hide fields.
  forms/admin.py
  forms/static/forms/admin/dependency_fields.js
Labels: enhancement

#69 Fix url views issue
  gmmp/urls.py
  reports/export_builder.py
  reports/forms.py
  reports/report_builder.py
  reports/urls.py
  reports/views.py
Labels: bug
