Repository CodeForAfrica/gmmp, pull requests merged in 2021-03, with the labels that each got.

#144 [Feature] import-weights command
  .env/.env.template
  Dockerfile
  docker-compose.yml
  gmmp/apps.py
  gmmp/settings.py
  reports/apps.py
  reports/management/commands/import-weights.py
  reports/migrations/0008_gsheetcountryweights.py
  reports/models.py
  reports/signals.py
  requirements-all.txt
  requirements-dev.txt
  requirements.txt
Labels: enhancement

#148 [HotFix] TV media type
  reports/migrations/0009_delete_tv_media_type.py
  reports/signals.py
Labels: bug

#146 [Fix] Sheet order
  reports/report_builder.py
Labels: bug

#147 [Feature] Covid stories: highlight gender inequalities, by major topic
  reports/report_builder.py
  reports/report_details.py
Labels: bug, enhancement

#145 [Feature] Covid stories: gender stereotypes, by major topic
  reports/report_builder.py
  reports/report_details.py
Labels: bug, enhancement

#149 [Feature] Covid stories: news subjects and sources, by function in the news, by sex
  reports/report_builder.py
  reports/report_details.py
Labels: enhancement

#150 [Feature] Covid stories: news subjects and sources, survivors by sex
  reports/report_builder.py
  reports/report_details.py
Labels: enhancement

#153 Updated queries for sheet 50-60
  reports/report_builder.py
  reports/report_details.py
Labels: enhancement

#154 [Feature] Sheet 106, Covid stories: news subjects and sources, occupation by sex
  reports/report_builder.py
  reports/report_details.py
Labels: enhancement

#157 [Feature] Special questions queries
  reports/report_builder.py
  reports/report_details.py
Labels: enhancement

#158 [Feature] s Queries for Question (Z)
  reports/report_builder.py
Labels: enhancement

#159 Ft update queries 4, 18 and 32
  reports/report_builder.py
Labels: enhancement

#161 Chore add sentry
  .env/.env.template
  gmmp/settings.py
  reports/report_builder.py
  requirements-all.txt
Labels: chore

#160 Fix buggy list comprehension.
  reports/report_builder.py
Labels: bug

#162 [Hoftix] Country mapping and recoding
  reports/report_builder.py
  reports/report_details.py
Labels: bug

#163 [Fix] Feedback
  reports/report_builder.py
  reports/report_details.py
Labels: bug

#165 [Feature] Weight sr queries
  reports/report_builder.py
  reports/report_details.py
Labels: enhancement

#166 Ft add overall statistic
  reports/report_builder.py
Labels: enhancement

#167 [Chore] Django 2.2.19
  requirements-all.txt
Labels: dependencies, security

#168 [Feature] Special questions yes/no count
  reports/report_builder.py
Labels: enhancement

#169 [Feature] Make Special Questions column the secondary column heading
  reports/report_builder.py
Labels: enhancement

#170 [HotFix] counts indentation
  reports/report_builder.py
Labels: bug
