Repository CodeForAfrica/gmmp, pull requests merged in 2021-02, with the labels that each got.

#119 import sheet 27, 31, 36, 38, 39, 45, 47, 49, 50 & 51
  historical.json
  reports/historical/_gmmp_2015_importer.py
  reports/report_details.py
Labels: enhancement

#120 Import sheets from 52, 55, 56, 59, 67, 73, s12, s26, s27, & sr08
  historical.json
  reports/historical/_gmmp_2015_importer.py
  reports/report_details.py
Labels: enhancement

#121 Import sr10 type sheets
  historical.json
  reports/historical/_base_importer.py
  reports/historical/_gmmp_2015_importer.py
  reports/report_details.py
Labels: enhancement

#122 Import double header sheets cont'd
  historical.json
  reports/historical/_gmmp_2015_importer.py
  reports/report_details.py
Labels: enhancement

#123 Import more double header sheets
  historical.json
  reports/historical/_gmmp_2015_importer.py
  reports/historical/utils/__init__.py
  reports/historical/utils/countries/__init__.py
  reports/historical/utils/countries/countries_for_57.py
  reports/historical/utils/countries/countries_for_58.py
  reports/historical/utils/countries/countries_for_60.py
  reports/historical/utils/countries/countries_for_66.py
  reports/report_details.py
Labels: enhancement

#124 Import sheets from 70
  historical.json
  reports/historical/_gmmp_2015_importer.py
  reports/historical/historical.py
  reports/report_details.py
Labels: enhancement

#131 Adds Missing worksheet methods.
  reports/report_builder.py
Labels: bug

#130 [Fix] Country, Region, Media, Weights
  gmmp/settings.py
  reports/migrations/0005_duplicate_weights.py
  reports/migrations/0006_unique_country_mediatype.py
  reports/migrations/0007_proxy_weights.py
  reports/models.py
  reports/report_builder.py
  reports/report_details.py
  requirements.txt
Labels: bug, enhancement

#132 Includes DM media types in historical report
  reports/report_builder.py
Labels: bug

#138 [Fix] Show ALPHA3 in raw sheets of the report
  docker-compose.yml
  reports/report_builder.py
Labels: bug

#139 Adds queries for sheet 100
  reports/report_builder.py
  reports/report_details.py
Labels: enhancement

#141 Update queries for sheet 100
  reports/report_builder.py
  reports/report_details.py
Labels: bug

#134 Adds Query for Sheet 101 + WS_INFO Cleanup
  reports/report_builder.py
  reports/report_details.py
Labels: enhancement
