Repository CodeForAfrica/gmmp, pull requests merged in 2021-04, with the labels that each got.

#171 Ensure every medium has it's own Counter.
  reports/report_builder.py
Labels: bug

#172 Fix sr05 to show all media types
  reports/report_builder.py
  reports/report_details.py
Labels: bug

#175 Removes transnational values from worksheet 28b, 28c regional reports
  reports/report_builder.py
Labels: bug

#176 Fixes bug caused by initializing counts at the wrong place
  reports/report_builder.py
Labels: bug

#174 Ft generate csv for use in wazimap
  reports/management/commands/generate_dataset.py
  reports/report_builder.py
  reports/report_dataset.py
Labels: enhancement

#179 Remove leading / from static URLs since it's causing issues in production
  gmmp/static/wazimap/index.html
Labels: bug

#180 [Chore] Upgrade dependencies
  gmmp/settings.py
  gmmp/urls.py
  requirements-all.txt
Labels: chore

#182 Add new countries reports
  reports/report_builder.py
  reports/report_details.py
  reports/views.py
Labels: bug, enhancement
